plugins { id 'com.android.application' }

android {
    namespace 'com.chenzecon.oznerftcdebug'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chenzecon.oznerftcdebug'
        minSdk 19
        targetSdk 22
        versionCode 2
        versionName '1.0-debug-wifi22'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
